spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pinyaskin/thesis-config
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}
          default-label: master
          search-paths: "{application}"

server:
  port: 8071